### ISSUE TITLE
Could you please share raw system matrices?

### ISSUE THREAD

**Issue by WrinkleXuan** [Ivo-B/3dSMRnet#4]
Thanks for your code！
The links of Perimag and Synomag-d are invalid!
Could you please offer new links?

**Comment by tknopp** [comment]
@Ivo-B: It seems that you have put the data into a google drive. Would it be possible to make a zeno do repository? See https://zenodo.org/record/7457743 for instance. You can also assign it to the "Magnetic Particle Imaging" community at zenodo.

**Comment by WrinkleXuan** [comment]
@tknopp thank you very much!

**Comment by Ivo-B** [comment]
Hi @WrinkleXuan, you can find the raw MPI data here:
[open-mpi-data](https://www.tuhh.de/ibi/open-science/open-mpi-data) 

At some point, I removed the data for the experiments from google drive. I uploaded them Zenodo now:
[https://zenodo.org/record/8124800](https://zenodo.org/record/8124800)

**Comment by WrinkleXuan** [comment]
> 



> Hi @WrinkleXuan, you can find the raw MPI data here: [open-mpi-data](https://www.tuhh.de/ibi/open-science/open-mpi-data)
> 
> At some point, I removed the data for the experiments from google drive. I uploaded them Zenodo now: https://zenodo.org/record/8124800

Thanks for your quick and useful answer!
